# Site URL where 12 Step WP Plugin is installed
site_url: https://baltimoreaa.org/

# Page size of the output PDF.
# If not doing Letter, prepare to use custom template_dirs and stylesheets
size: Letter #  5.5in 8.5in

# Background css color of the cover and page headers
color: lightblue

# Metadata info about who makes this PDF
author: Baltimore Intergroup Council
description: Baltimore Area A.A. Group meeting Directory
address: 8635 Loch Raven Boulevard, Suite 4 • Baltimore, Maryland 21286
phone: 410-663-1922
fax: 410-663-7465
email: intergroup@baltimoreaa.org
website: www.baltimoreaa.org

# Template directories.
# Create your own directory and add it here to override default emplates
# template_dirs:
#     - my/custom/templates

# CSS stylesheets to add when rendering PDF
# Add your own to modify styles
# stylesheets:
#     - my/path/to/custom.css

# Show links or not when rendering
show_links: true

# Codes to filter out from displaying
# Removes them from PDF entirely
filtercodes:
    - TC # Temporarily closed

# Set this to display only these attendance_options in the PDF
# Normal options are in_person, inactive, online, andhybrid
# Used to only print hybrid/in_person for print PDF
# attendance_options:
#     - in_person
#     - hybrid
#     - online
#     - inactive

# Maps a system code to a new code to display in the directory
codemap:
    B: BB
    BE: BEG
    S: SPAN
    ST: STEP
    TR: TRAD
    X: H

# System meeting codes and their descriptions.
# Do not modify the keys on this mapping, this is from the plugin
# Feel free to change descriptions or add your own
meetingcodes:
    11: 11th Step Meditation
    12x12: 12 Steps & 12 Traditions
    ABSI: As Bill Sees It
    B: Big Book
    BE: Beginner/Newcomer
    C: Closed Meeting for Alcoholics Only
    CAN: Candlelight
    CF: Child-Friendly
    CPTS: Concepts
    D: Discussion
    DB: Digital Basket
    DR: Daily Reflections
    GR: Grapevine
    HYB: Hybrid
    LGBTQ: LGBTQ
    LIT: Literature
    LS: Living Sober
    M: Men's
    MED: Meditation
    NB: Non-Binary
    O: Open
    ONL: Online
    OUT: Outdoor Meeting
    POC: People of Color
    S: Spanish Speaking
    SEN: Seniors
    SP: Speaker
    ST: Step Meeting
    T: Transgender
    TC: Temporarily Closed
    TR: Tradition Study
    W: Women's
    X: Handicap Access
    Y: Young People's

# Locztions by zipcode with their neighborhood name
zipcodes:
    Annapolis: 21401
    Arbutus/Halethorpe: 21227
    Arcadia, Upperco: 21155
    Bel Air, Forest Hill: 21014
    Belair-Edison: 21213
    Bolton Hill: 21217
    Bowie: 20715
    Brooklyn: 21225
    Butler: 21023
    Canton/Highlandtown: 21224
    Catonsville: 21228
    Clarksville: 21029
    Cockeysville, Hunt Valley:
    - 21030
    - 21031
    College Park: 20705
    Columbia:
    - 21044
    - 21045
    - 21046
    Crownsville: 21032
    Curtis Bay: 21226
    Dorsey: 21077
    Downtown Baltimore:
    - 21202
    - 21201
    Dundalk: 21222
    Edgewater: 21037
    Edgewood:
    - 21085
    - 21040
    Elkridge: 21075
    Elkton: 21921
    Ellicott City:
    - 21041
    - 21043
    - 21042
    Essex, Middle River: 21221
    Fallston: 21047
    Federal Hill, South Baltimore: 21230
    Fells Point: 21231
    Finksburg: 21048
    Forest Hill: 21050
    Frederick: 21704
    Freeland: 21053
    Fullerton/Perry Hall: 21128
    Glen Arm: 21057
    Glen Burnie:
    - 21061
    - 21060
    Glenelg: 21737
    Glenwood: 21738
    Govans/Rogers Forge: 21212
    Gyndon: 21071
    Hamilton: 21214
    Hampden: 21211
    Hampstead: 21074
    Hanover: 21076
    Hydes, Long Green: 21082
    Jacksonville, Phoenix: 21131
    Jessup: 20794
    Kingsville: 21087
    Laurel:
    - 20723
    - 20707
    Linthicum: 21090
    Lutherville/Timonium: 21093
    Manchester: 21102
    Marriottsville: 21104
    Middle East, Clifton: 21205
    Middle River, Bowleys Quarters: 21220
    Millersville: 21108
    Monkton: 21111
    Mount Airy: 21771
    New Windsor: 21776
    Northwood/Idlewylde: 21239
    Nottingham: 21236
    Overlea: 21206
    Owings Mills: 21117
    Park Heights: 21215
    Parkton: 21120
    Parkville: 21234
    Pasadena: 21122
    Pikesville:
    - 21208
    - 21209
    Randallstown: 21133
    Reisterstown: 21136
    Roland Park: 21210
    Rosedale: 21237
    Severn: 21144
    Severna Park: 21146
    Silver Spring: 20910
    Southwest Baltimore: 21223
    Sparks: 21152
    Sparrows Point, Edgemere: 21219
    Sykesville/Eldersburg: 21784
    Taneytown: 21787
    Towson:
    - 21286
    - 21204
    Union Bridge: 21791
    Waverly/Charles Village: 21218
    West Baltimore: 21229
    West Friendship: 21794
    Westminster:
    - 21158
    - 21157
    White Marsh: 21162
    Windsor Mill: 21244
    Woodlawn: 21207
    Woodstock: 21163
